name: dashboard Deploy

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      -
        name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      -
        name: Setup Node
        uses: actions/setup-node@v2.4.0
        with:
          node-version: "16"
      -
        name: Setup Dependencies
        run: yarn install
      -
        name: Build Site
        run: npm run build
      -
        name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          publish_branch: dist
          publish_dir: ./dist
      -
        name: Publish To ShenYu
        run: |
            git clone https://github.com/apache/shenyu.git shenyu
            pwd
            ls -a
            cd shenyu
            ls -a
            pwd
            git checkout -b shenyu_dashboard
            rm -rf shenyu-admin/src/main/resources/static/*
            cp -r ../dist/* shenyu-admin/src/main/resources/static/
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add .

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
